# Generated by Django 5.1.3 on 2024-11-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_correct_answer_correctquestions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
