# Generated by Django 5.1.3 on 2024-11-23 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_quiz_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Aquiz',
        ),
        migrations.RenameModel(
            old_name='CorrectQuestions',
            new_name='CorrectQuestion',
        ),
        migrations.RenameModel(
            old_name='Answer',
            new_name='Zanswer',
        ),
    ]
